import { useState, useCallback } from 'react';
import { query, queryOne, execute } from '@/lib/database';
import type { Entree, EntreeWithCategorie, Sortie, Reversement, Exercice } from '@/types';

export function useFinance() {
  const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const addEntree = useCallback(async (data: Omit<Entree, 'id' | 'created_at'>) => { setLoading(true); setError(null); try { const id = await execute(`INSERT INTO entrees (date, culte, categorie_id, devise, montant, montant_cdf, montant_usd, note) VALUES (?, ?, ?, ?, ?, ?, ?, ?)`, [data.date, data.culte, data.categorie_id, data.devise, data.montant, data.montant_cdf, data.montant_usd, data.note]); const row = await queryOne<EntreeWithCategorie>('SELECT e.*, c.nom categorie_nom FROM entrees e JOIN categories c ON e.categorie_id=c.id WHERE e.id=?',[id]); setLoading(false); return row; } catch (e) { setError(e instanceof Error ? e.message : 'Erreur'); setLoading(false); return null; } }, []);
  const addSortie = useCallback(async (data: Omit<Sortie, 'id' | 'created_at'>) => { setLoading(true); setError(null); try { const id = await execute(`INSERT INTO sorties (date,nature,devise,montant,montant_cdf,montant_usd,description,nom_operateur,telephone_operateur) VALUES (?,?,?,?,?,?,?,?,?)`, [data.date,data.nature,data.devise,data.montant,data.montant_cdf,data.montant_usd,data.description,data.nom_operateur,data.telephone_operateur]); const row=await queryOne<Sortie>('SELECT * FROM sorties WHERE id=?',[id]); setLoading(false); return row; } catch(e) { setError(e instanceof Error ? e.message : 'Erreur'); setLoading(false); return null; } }, []);
  const addReversement = useCallback(async (data: Omit<Reversement, 'id' | 'created_at'>) => { setLoading(true); try { const id=await execute(`INSERT INTO reversements (type,montant_cdf,montant_usd,date_reversement,periode_debut,periode_fin) VALUES (?,?,?,?,?,?)`,[data.type,data.montant_cdf,data.montant_usd,data.date_reversement,data.periode_debut,data.periode_fin]); const row=await queryOne<Reversement>('SELECT * FROM reversements WHERE id=?',[id]); setLoading(false); return row; } catch(e) { setError(e instanceof Error ? e.message : 'Erreur'); setLoading(false); return null; } }, []);
  const getEntrees=useCallback((start:string,end:string)=>query<EntreeWithCategorie>('SELECT e.*,c.nom categorie_nom FROM entrees e JOIN categories c ON e.categorie_id=c.id WHERE e.date>=? AND e.date<=? ORDER BY e.date DESC',[start,end]),[]);
  const getSorties=useCallback((start:string,end:string)=>query<Sortie>('SELECT * FROM sorties WHERE date>=? AND date<=? ORDER BY date DESC',[start,end]),[]);
  const getReversements=useCallback((start:string,end:string)=>query<Reversement>('SELECT * FROM reversements WHERE date_reversement>=? AND date_reversement<=? ORDER BY date_reversement DESC',[start,end]),[]);
  const getAllEntrees=useCallback(()=>query<EntreeWithCategorie>('SELECT e.*,c.nom categorie_nom FROM entrees e JOIN categories c ON e.categorie_id=c.id ORDER BY e.date ASC'),[]);
  const getAllSorties=useCallback(()=>query<Sortie>('SELECT * FROM sorties ORDER BY date ASC'),[]);
  const getAllReversements=useCallback(()=>query<Reversement>('SELECT * FROM reversements ORDER BY date_reversement ASC'),[]);
  const getExercice=useCallback((year:number)=>queryOne<Exercice>('SELECT * FROM exercices WHERE annee=?',[year]),[]);
  const getMonthlyTotals=useCallback(async(year:number)=>{const start=`${year}-01-01`,end=`${year}-12-31`; const [entrees,sorties,reversements]=await Promise.all([query<EntreeWithCategorie>('SELECT e.*,c.nom categorie_nom FROM entrees e JOIN categories c ON e.categorie_id=c.id WHERE e.date>=? AND e.date<=? ORDER BY e.date ASC',[start,end]),query<Sortie>('SELECT * FROM sorties WHERE date>=? AND date<=? ORDER BY date ASC',[start,end]),query<Reversement>('SELECT * FROM reversements WHERE date_reversement>=? AND date_reversement<=? ORDER BY date_reversement ASC',[start,end])]); const monthlyEntreesCdf=Array(12).fill(0),monthlyEntreesUsd=Array(12).fill(0),monthlySortiesCdf=Array(12).fill(0),monthlySortiesUsd=Array(12).fill(0),monthlyReversementsCdf=Array(12).fill(0),monthlyReversementsUsd=Array(12).fill(0); for(const e of entrees){const m=new Date(e.date).getMonth();monthlyEntreesCdf[m]+=e.montant_cdf;monthlyEntreesUsd[m]+=e.montant_usd;} for(const s of sorties){const m=new Date(s.date).getMonth();monthlySortiesCdf[m]+=s.montant_cdf;monthlySortiesUsd[m]+=s.montant_usd;} for(const r of reversements){const m=new Date(r.date_reversement).getMonth();monthlyReversementsCdf[m]+=r.montant_cdf;monthlyReversementsUsd[m]+=r.montant_usd;} return {monthlyEntreesCdf,monthlyEntreesUsd,monthlySortiesCdf,monthlySortiesUsd,monthlyReversementsCdf,monthlyReversementsUsd,entrees,sorties,reversements};},[]);
  const deleteAllEntrees=useCallback(()=>execute('DELETE FROM entrees WHERE id>0'),[]),deleteAllSorties=useCallback(()=>execute('DELETE FROM sorties WHERE id>0'),[]),deleteAllReversements=useCallback(()=>execute('DELETE FROM reversements WHERE id>0'),[]);
  const archiveExercice=useCallback((annee:number,totalEntrees:number,totalSorties:number,totalReversements:number,donnees:string)=>execute('INSERT INTO exercices (annee,total_entrees,total_sorties,total_reversements,donnees) VALUES (?,?,?,?,?)',[annee,totalEntrees,totalSorties,totalReversements,donnees]),[]);
  return {loading,error,addEntree,addSortie,addReversement,getEntrees,getSorties,getReversements,getAllEntrees,getAllSorties,getAllReversements,getExercice,getMonthlyTotals,deleteAllEntrees,deleteAllSorties,deleteAllReversements,archiveExercice};
}
