import { useState } from 'react';
import { ArrowLeft, Save, X, Calendar, Tag, DollarSign, FileText, CheckCircle2 } from 'lucide-react';
import type { Config, Categorie, Devise } from '@/types';
import { CULTE_OPTIONS } from '@/types';
import { useFinance } from '@/hooks/useFinance';
import { todayISO, formatCurrency } from '@/utils/format';
import { generateRecuEntree } from '@/services/pdf';

interface EntryFormProps { config: Config; categories: Categorie[]; onBack: () => void; }

export function EntryForm({ config, categories, onBack }: EntryFormProps) {
  const { addEntree } = useFinance();
  const [date, setDate] = useState(todayISO()); const [culte, setCulte] = useState<string>(CULTE_OPTIONS[0]);
  const [categorieId, setCategorieId] = useState(categories[0]?.id || 0); const [devise, setDevise] = useState<Devise>('CDF');
  const [montant, setMontant] = useState(''); const [note, setNote] = useState(''); const [success, setSuccess] = useState(false); const [error, setError] = useState<string | null>(null);
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); const value = parseInt(montant, 10); if (!value || value <= 0) { setError('Veuillez entrer un montant valide'); return; } const result = await addEntree({ date, culte, categorie_id: categorieId, devise, montant: value, montant_cdf: devise === 'CDF' ? value : 0, montant_usd: devise === 'USD' ? value : 0, note: note || null }); if (result) { generateRecuEntree(config, result, categories.find(c => c.id === categorieId)?.nom || ''); setSuccess(true); setTimeout(onBack, 1800); } else setError("Erreur lors de l'enregistrement"); };
  if (success) return <div className="min-h-[60vh] flex items-center justify-center"><div className="text-center"><CheckCircle2 className="w-16 h-16 text-emerald-600 mx-auto" /><h3 className="text-xl font-bold mt-4">Entrée enregistrée</h3><p className="text-gray-500">Le reçu PDF a été téléchargé</p></div></div>;
  return <div className="max-w-2xl mx-auto"><div className="flex items-center gap-3 mb-6"><button onClick={onBack} className="p-2 rounded-lg bg-gray-100"><ArrowLeft className="w-5 h-5" /></button><h1 className="text-2xl font-bold">Enregistrer une Entrée</h1></div><form onSubmit={handleSubmit} className="bg-white rounded-2xl shadow-sm border p-6 space-y-5"><label className="block text-sm font-medium">Date<input type="date" value={date} onChange={e => setDate(e.target.value)} className="mt-2 w-full px-4 py-2.5 border rounded-xl" /></label><label className="block text-sm font-medium">Culte / Service<select value={culte} onChange={e => setCulte(e.target.value)} className="mt-2 w-full px-4 py-2.5 border rounded-xl">{CULTE_OPTIONS.map(c => <option key={c}>{c}</option>)}</select></label><label className="block text-sm font-medium">Nature de la recette<select value={categorieId} onChange={e => setCategorieId(parseInt(e.target.value, 10))} className="mt-2 w-full px-4 py-2.5 border rounded-xl">{categories.map(c => <option key={c.id} value={c.id}>{c.nom}</option>)}</select></label><div><label className="block text-sm font-medium mb-2">Devise de la caisse</label><div className="flex gap-3"><button type="button" onClick={() => setDevise('CDF')} className={`flex-1 py-2.5 rounded-xl border ${devise === 'CDF' ? 'bg-emerald-600 text-white' : 'bg-gray-50'}`}>Caisse CDF</button><button type="button" onClick={() => setDevise('USD')} className={`flex-1 py-2.5 rounded-xl border ${devise === 'USD' ? 'bg-emerald-600 text-white' : 'bg-gray-50'}`}>Caisse USD</button></div></div><label className="block text-sm font-medium">Montant ({devise})<input type="number" value={montant} onChange={e => setMontant(e.target.value)} min="1" className="mt-2 w-full px-4 py-2.5 border rounded-xl text-lg font-semibold" />{montant && <p className="text-sm text-emerald-600 mt-1">Caisse {devise}: {formatCurrency(parseInt(montant, 10) || 0, devise)}</p>}</label><label className="block text-sm font-medium">Note (optionnel)<textarea value={note} onChange={e => setNote(e.target.value)} rows={3} className="mt-2 w-full px-4 py-2.5 border rounded-xl" /></label>{error && <div className="bg-red-50 text-red-700 px-4 py-3 rounded-xl text-sm">{error}</div>}<div className="flex gap-3"><button type="submit" className="flex-1 py-3 bg-emerald-600 text-white font-semibold rounded-xl flex items-center justify-center gap-2"><Save className="w-5 h-5" />Enregistrer</button><button type="button" onClick={onBack} className="flex-1 py-3 bg-gray-100 rounded-xl flex items-center justify-center gap-2"><X className="w-5 h-5" />Annuler</button></div></form></div>;
}
