import { useState } from 'react';
import { ArrowLeft, Save, X, Calendar, Tag, DollarSign, FileText, Lock, User, Phone, CheckCircle2 } from 'lucide-react';
import type { Config, Devise } from '@/types';
import { useFinance } from '@/hooks/useFinance';
import { todayISO, formatCurrency } from '@/utils/format';
import { generateRecuSortie } from '@/services/pdf';

interface ExitFormProps { config: Config; onBack: () => void; }
export function ExitForm({ config, onBack }: ExitFormProps) {
  const { addSortie } = useFinance(); const [date, setDate] = useState(todayISO()); const [nature, setNature] = useState(''); const [devise, setDevise] = useState<Devise>('CDF'); const [montant, setMontant] = useState(''); const [description, setDescription] = useState(''); const [password, setPassword] = useState(''); const [nomOperateur, setNomOperateur] = useState(''); const [telOperateur, setTelOperateur] = useState(''); const [success, setSuccess] = useState(false); const [error, setError] = useState<string | null>(null);
  const handleSubmit = async (e: React.FormEvent) => { e.preventDefault(); const value = parseInt(montant, 10); if (password !== config.mdp_sortie) return setError('Mot de passe de confirmation incorrect'); if (!value || value <= 0) return setError('Veuillez entrer un montant valide'); if (!nature.trim() || !nomOperateur.trim() || !telOperateur.trim()) return setError('Veuillez remplir tous les champs obligatoires'); const result = await addSortie({ date, nature: nature.trim(), devise, montant: value, montant_cdf: devise === 'CDF' ? value : 0, montant_usd: devise === 'USD' ? value : 0, description: description || null, nom_operateur: nomOperateur.trim(), telephone_operateur: telOperateur.trim() }); if (result) { generateRecuSortie(config, result); setSuccess(true); setTimeout(onBack, 1800); } else setError("Erreur lors de l'enregistrement"); };
  if (success) return <div className="min-h-[60vh] flex items-center justify-center"><div className="text-center"><CheckCircle2 className="w-16 h-16 text-emerald-600 mx-auto" /><h3 className="text-xl font-bold mt-4">Sortie enregistrée</h3><p className="text-gray-500">Le reçu PDF a été téléchargé</p></div></div>;
  return <div className="max-w-2xl mx-auto"><div className="flex items-center gap-3 mb-6"><button onClick={onBack} className="p-2 rounded-lg bg-gray-100"><ArrowLeft className="w-5 h-5" /></button><h1 className="text-2xl font-bold">Enregistrer une Sortie</h1></div><form onSubmit={handleSubmit} className="bg-white rounded-2xl shadow-sm border p-6 space-y-5"><label className="block text-sm font-medium">Date<input type="date" value={date} onChange={e => setDate(e.target.value)} className="mt-2 w-full px-4 py-2.5 border rounded-xl" /></label><label className="block text-sm font-medium">Nature du décaissement<input value={nature} onChange={e => setNature(e.target.value)} className="mt-2 w-full px-4 py-2.5 border rounded-xl" /></label><div><label className="block text-sm font-medium mb-2">Devise de la caisse</label><div className="flex gap-3"><button type="button" onClick={() => setDevise('CDF')} className={`flex-1 py-2.5 rounded-xl border ${devise === 'CDF' ? 'bg-red-600 text-white' : 'bg-gray-50'}`}>Caisse CDF</button><button type="button" onClick={() => setDevise('USD')} className={`flex-1 py-2.5 rounded-xl border ${devise === 'USD' ? 'bg-red-600 text-white' : 'bg-gray-50'}`}>Caisse USD</button></div></div><label className="block text-sm font-medium">Montant ({devise})<input type="number" value={montant} onChange={e => setMontant(e.target.value)} min="1" className="mt-2 w-full px-4 py-2.5 border rounded-xl text-lg font-semibold" />{montant && <p className="text-sm text-red-600 mt-1">Caisse {devise}: {formatCurrency(parseInt(montant, 10) || 0, devise)}</p>}</label><label className="block text-sm font-medium">Description<textarea value={description} onChange={e => setDescription(e.target.value)} rows={3} className="mt-2 w-full px-4 py-2.5 border rounded-xl" /></label><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="block text-sm font-medium">Nom de l'opérateur<input value={nomOperateur} onChange={e => setNomOperateur(e.target.value)} className="mt-2 w-full px-4 py-2.5 border rounded-xl" /></label><label className="block text-sm font-medium">Téléphone<input type="tel" value={telOperateur} onChange={e => setTelOperateur(e.target.value)} className="mt-2 w-full px-4 py-2.5 border rounded-xl" /></label></div><label className="block text-sm font-medium">Mot de passe de confirmation<input type="password" value={password} onChange={e => setPassword(e.target.value)} className="mt-2 w-full px-4 py-2.5 border rounded-xl" /></label>{error && <div className="bg-red-50 text-red-700 px-4 py-3 rounded-xl text-sm">{error}</div>}<div className="flex gap-3"><button type="submit" className="flex-1 py-3 bg-red-600 text-white font-semibold rounded-xl flex items-center justify-center gap-2"><Save className="w-5 h-5" />Enregistrer</button><button type="button" onClick={onBack} className="flex-1 py-3 bg-gray-100 rounded-xl flex items-center justify-center gap-2"><X className="w-5 h-5" />Annuler</button></div></form></div>;
}
